### ISSUE TITLE
Section 9 on subquery coercion defines inconsistent(?) behavior

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang#3]
> For compatibility with SQL, a SFW subquery
starting with a SELECT clause (as opposed to a subquery starting with SELECT VALUE or PIVOT) coerces into a scalar or
into an array, depending on the context.

The spec states that we do not coerce 

```
SELECT v AS k FROM T               -- A
SELECT VALUE { 'k': v } FROM T     -- B

a = (SELECT v AS k FROM T)             -- C
a = (SELECT VALUE { 'k': v } FROM T)   -- D

a = COLL_TO_SCALAR(SELECT v AS k FROM T)    -- E
```

If `A <=> B` then how can we say `C != D`? This feels like a gotcha or perhaps the spec needs more details on *which* kinds of SELECT VALUE. Perhaps it should read `SELECT VALUE with non-tuple constructor`.

I think a subtlety that is important is that, in this case, `A != B` because the use of the SQL SELECT has a different meaning than the SELECT-VALUE rewrite.

**Comment by johnedquinn** [comment]
Found some excerpts from the PartiQL Specification that give insight into why this is the case.

> SQL’s well-known SELECT clause can be used as a mere syntactic sugar over SELECT VALUE, when we consider
the top-level query. In particular, Section 6.3 shows that SQL’s SELECT is the special case where the SELECT VALUE
produces collections of tuples. Furthermore, when SELECT is used as a subquery it is coerced into a scalar or a tuple,
in the ways that SQL coerces the results of subqueries.
>
> -- Section 6: SELECT clauses


> A SFW subquery may appear in the SELECT VALUE clause of a query, enabling the creation of nested
results.
>
> -- Section 6.4: Examples with combinations of multiple features:

**Comment by rchowell** [comment]
I think the important thing to note here is `A != B` in all cases. The context of where the SFW query appears changes the meaning of the SQL SELECT. It's sugar only when not in a coerceable context
